ADD_EVENT: str = "-ADD-"
SAVE_EVENT: str = "-SAVE-"
SAVE_CLOSE_EVENT: str = "-SAVE-CLOSE-"
EDIT_EVENT: str = "-EDIT-"
DELETE_EVENT: str = "-DEL-"
EXIT_EVENT: str = "Exit"
VERSION_EVENT: str = "Version"
DEFAULT_EVENT: str = "-DEFAULT-"
