TITLE_KEY = "-Title-"
DUE_DATE_KEY: str = "-DueDate-"
CATEGORY_KEY: str = "-Category-"
DESCRIPTION_KEY: str = "-Description-"
NOTES_KEY: str = "-Notes-"
TODO_LIST_KEY: str  = "-TODO LIST-"
ROW_KEY: str = "-ROW-"